/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mycompany.swigtest;

public class swigtest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected swigtest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(swigtest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TestJNI.delete_swigtest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public swigtest() {
    this(TestJNI.new_swigtest(), true);
  }

  public int GetNumber() {
    return TestJNI.swigtest_GetNumber(swigCPtr, this);
  }

}
