/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mycompany.swigtest;

public class TestJNI {
  public final static native long new_swigtest();
  public final static native void delete_swigtest(long jarg1);
  public final static native int swigtest_GetNumber(long jarg1, swigtest jarg1_);
}
